// All possible audit log action names in one place.
// Kept as a const object (not a TS enum) for the same isolatedModules
// reasons as Role — easier to import as a value-type pair.
export const AuditAction = {
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_PASSWORD_RESET_REQUESTED: 'USER_PASSWORD_RESET_REQUESTED',
  USER_PASSWORD_RESET_COMPLETED: 'USER_PASSWORD_RESET_COMPLETED',

  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_DEACTIVATED: 'USER_DEACTIVATED',
  USER_REACTIVATED: 'USER_REACTIVATED',
  USER_PASSWORD_SET_BY_ADMIN: 'USER_PASSWORD_SET_BY_ADMIN',

  INVOICE_UPLOADED: 'INVOICE_UPLOADED',
  INVOICE_EDITED: 'INVOICE_EDITED',
  INVOICE_DELETED: 'INVOICE_DELETED',
  INVOICE_RESCANNED: 'INVOICE_RESCANNED',

  STATEMENT_UPLOADED: 'STATEMENT_UPLOADED',
  STATEMENT_DELETED: 'STATEMENT_DELETED',

  CARD_CREATED: 'CARD_CREATED',
  CARD_UPDATED: 'CARD_UPDATED',
  CARD_ASSIGNED: 'CARD_ASSIGNED',
  CARD_DELETED: 'CARD_DELETED',

  RECON_RUN: 'RECON_RUN',
  RECON_MATCH_MANUAL: 'RECON_MATCH_MANUAL',
  RECON_UNLINK: 'RECON_UNLINK',

  EDIT_REQUEST_CREATED: 'EDIT_REQUEST_CREATED',
  EDIT_REQUEST_APPROVED: 'EDIT_REQUEST_APPROVED',
  EDIT_REQUEST_REJECTED: 'EDIT_REQUEST_REJECTED',

  // Admin nudged the cardholder about an unmatched transaction.
  INVOICE_REQUESTED: 'INVOICE_REQUESTED',
} as const;

export type AuditAction = (typeof AuditAction)[keyof typeof AuditAction];
